name: Node.js CI/CD

on:
  push:
    branches: 
      - main

jobs:
  build_ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    # - name: Build and test
    #   run: npm test

  deploy_cd:
    needs: build_ci
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: "${{ secrets.EC2_FOLDER }}"
        remote_host: "${{ secrets.EC2_HOST }}"
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: SSH into VPS and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          npm install
          sudo pm2 delete backend
          sudo pm2 start index.js --name backend